openapi: 3.0.3
info:
    title: Student Login Logger - OpenAPI 3.0
    description: |-
        This is the documentation for the RIT SL2 API. You can find out more about the SL2 at [https://github.com/Dragoffs](https://github.com/Dragoffs)

        Some useful links:
        - [Application Repository](https://github.com/Dragoffs/SL2)
    contact:
        email: dec8768@rit.edu
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.11
paths:
    /login:
        post:
            tags:
                - Authentication
            summary: Login as a user
            description: Authenticate a user using email and password.
            operationId: User Authentication.
            parameters:
                - name: email
                  in: body
                  description: Email of the user
                  required: true
                  schema:
                      type: string
                      example: Fredrick.Tal@rit.edu
                - name: password
                  in: body
                  description: Password of the user
                  required: true
                  schema:
                      type: string
                      example: test
            requestBody:
                description: Authenticate a user with email and password.
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Authentication"
                required: true
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/puid"
                "404":
                    description: User not found
                "500":
                    description: Server failure.
            security:
                - petstore_auth:
                      - write:pets
                      - read:pets
    /students/classid/{classId}:
        get:
            tags:
                - Student
            summary: Returns all students by class ids,
            description: Given a class id, return all of the students enrolled in this class.
            operationId: getStudentsByClassId
            parameters:
                - name: classId
                  in: path
                  description: Classid associated to the class.
                  required: true
                  schema:
                      type: string
                      example: ISTE 140-1
            responses:
                "200":
                    description: successful operation
                "500":
                    description: Server error
    /students/uid/uid:
        get:
            tags:
                - Student
            summary: Get student by their University ID.
            description: Getting students by the university id.
            operationId: getStudentsByUID
            parameters:
                - name: uid
                  in: path
                  description: Student's university ID
                  required: true
                  schema:
                      type: string
                      example: 41033822
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Pet"
                "500":
                    description: Server error
            security:
                - petstore_auth:
                      - write:pets
                      - read:pets
    /pet/{petId}:
        get:
            tags:
                - pet
            summary: Find pet by ID
            description: Returns a single pet
            operationId: getPetById
            parameters:
                - name: petId
                  in: path
                  description: ID of pet to return
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Pet"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Pet"
                "400":
                    description: Invalid ID supplied
                "404":
                    description: Pet not found
            security:
                - api_key: []
                - petstore_auth:
                      - write:pets
                      - read:pets
        post:
            tags:
                - pet
            summary: Updates a pet in the store with form data
            description: ""
            operationId: updatePetWithForm
            parameters:
                - name: petId
                  in: path
                  description: ID of pet that needs to be updated
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: name
                  in: query
                  description: Name of pet that needs to be updated
                  schema:
                      type: string
                - name: status
                  in: query
                  description: Status of pet that needs to be updated
                  schema:
                      type: string
            responses:
                "405":
                    description: Invalid input
            security:
                - petstore_auth:
                      - write:pets
                      - read:pets
        delete:
            tags:
                - pet
            summary: Deletes a pet
            description: delete a pet
            operationId: deletePet
            parameters:
                - name: api_key
                  in: header
                  description: ""
                  required: false
                  schema:
                      type: string
                - name: petId
                  in: path
                  description: Pet id to delete
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "400":
                    description: Invalid pet value
            security:
                - petstore_auth:
                      - write:pets
                      - read:pets
    /pet/{petId}/uploadImage:
        post:
            tags:
                - pet
            summary: uploads an image
            description: ""
            operationId: uploadFile
            parameters:
                - name: petId
                  in: path
                  description: ID of pet to update
                  required: true
                  schema:
                      type: integer
                      format: int64
                - name: additionalMetadata
                  in: query
                  description: Additional Metadata
                  required: false
                  schema:
                      type: string
            requestBody:
                content:
                    application/octet-stream:
                        schema:
                            type: string
                            format: binary
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ApiResponse"
            security:
                - petstore_auth:
                      - write:pets
                      - read:pets
    /store/inventory:
        get:
            tags:
                - store
            summary: Returns pet inventories by status
            description: Returns a map of status codes to quantities
            operationId: getInventory
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    type: integer
                                    format: int32
            security:
                - api_key: []
    /store/order:
        post:
            tags:
                - store
            summary: Place an order for a pet
            description: Place a new order in the store
            operationId: placeOrder
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Order"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Order"
                    application/x-www-form-urlencoded:
                        schema:
                            $ref: "#/components/schemas/Order"
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                "405":
                    description: Invalid input
    /store/order/{orderId}:
        get:
            tags:
                - store
            summary: Find purchase order by ID
            description: For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
            operationId: getOrderById
            parameters:
                - name: orderId
                  in: path
                  description: ID of order that needs to be fetched
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "200":
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Order"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Order"
                "400":
                    description: Invalid ID supplied
                "404":
                    description: Order not found
        delete:
            tags:
                - store
            summary: Delete purchase order by ID
            description: For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
            operationId: deleteOrder
            parameters:
                - name: orderId
                  in: path
                  description: ID of the order that needs to be deleted
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                "400":
                    description: Invalid ID supplied
                "404":
                    description: Order not found
components:
    schemas:
        Authentication:
            type: object
            properties:
                email:
                    type: string
                    example: Fredrick.Tal@rit.edu
                password:
                    type: string
                    example: test
            xml:
                name: order
        puid:
            type: string
            example: 42ad65ac759ccc385
            xml:
                name: customer
        Address:
            type: object
            properties:
                street:
                    type: string
                    example: 437 Lytton
                city:
                    type: string
                    example: Palo Alto
                state:
                    type: string
                    example: CA
                zip:
                    type: string
                    example: "94301"
            xml:
                name: address
        Category:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 1
                name:
                    type: string
                    example: Dogs
            xml:
                name: category
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 10
                username:
                    type: string
                    example: theUser
                firstName:
                    type: string
                    example: John
                lastName:
                    type: string
                    example: James
                email:
                    type: string
                    example: john@email.com
                password:
                    type: string
                    example: "12345"
                phone:
                    type: string
                    example: "12345"
                userStatus:
                    type: integer
                    description: User Status
                    format: int32
                    example: 1
            xml:
                name: user
        Tag:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
            xml:
                name: tag
        Pet:
            required:
                - name
                - photoUrls
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    example: 10
                name:
                    type: string
                    example: doggie
                category:
                    $ref: "#/components/schemas/Category"
                photoUrls:
                    type: array
                    xml:
                        wrapped: true
                    items:
                        type: string
                        xml:
                            name: photoUrl
                tags:
                    type: array
                    xml:
                        wrapped: true
                    items:
                        $ref: "#/components/schemas/Tag"
                status:
                    type: string
                    description: pet status in the store
                    enum:
                        - available
                        - pending
                        - sold
            xml:
                name: pet
        ApiResponse:
            type: object
            properties:
                code:
                    type: integer
                    format: int32
                type:
                    type: string
                message:
                    type: string
            xml:
                name: "##default"
    requestBodies:
        Pet:
            description: Pet object that needs to be added to the store
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Pet"
                application/xml:
                    schema:
                        $ref: "#/components/schemas/Pet"
        UserArray:
            description: List of user object
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            $ref: "#/components/schemas/User"
    securitySchemes:
        petstore_auth:
            type: oauth2
            flows:
                implicit:
                    authorizationUrl: https://petstore3.swagger.io/oauth/authorize
                    scopes:
                        write:pets: modify pets in your account
                        read:pets: read your pets
        api_key:
            type: apiKey
            name: api_key
            in: header
